---
- # Main playbook for setting up my Mac OS
  hosts: all
  connection: local

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/*.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      when: homebrew_installed_packages or homebrew_cask_apps
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - include_tasks: tasks/ansible-setup.yml
      tags: ['always']

    - include_tasks: tasks/dotfiles.yml
      tags: ['always']
