---
- # Main playbook for setting up my Mac OS
  hosts: all
  connection: local

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/*.yml"
      tags: ['always']

  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
