---
- name: Ensure settings directory exists
  file:
    path: "{{ settings_dir }}"
    state: directory

- name: Ensure zsh settings folder exists
  file:
    path: "{{ zsh_settings_dir }}"
    state: directory

- name: Ensure .config folder exists
  file:
    path: ~/.config
    state: directory
    mode: 0755

- name: Copy simple dotfiles
  copy:
    src: "{{ item }}"
    dest: ~/{{ item }}
    mode: 0640
  with_items:
    - .gitconfig

- name: Copy templated dotfiles
  template:
    src: "{{ item }}.j2"
    dest: ~/{{ item }}
    mode: 0640
  with_items:
    - .zshrc
    - .zprofile

- name: Copy zsh env vars
  template:
    src: envvars.zsh.j2
    dest: "{{ settings_dir }}/envvars.zsh"
    mode: 0640

- name: Copy zsh settings
  copy:
    src: "{{ item }}"
    dest: "{{ zsh_settings_dir }}"
    mode: 0644
  with_items:
    - alias.zsh
    - et.zsh
    - options.zsh

- name: Copy templated zsh settings
  template:
    src: {{ item }}.j2
    dest: "{{ zsh_settings_dir }}"/{{ item }}
    mode: 0640
  with_items:
    - conda.zsh

- name: Ensure ssh config dir exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Copy ssh config
  copy:
    src: sshconfig
    dest: ~/.ssh/config
    mode: 0600

- name: Ensure git config dir exists
  file:
    path: ~/.config/git
    state: directory
    mode: 0700

- name: Copy git global ignores
  copy:
    src: gitignore
    dest: ~/.config/git/ignores
    mode: 0640

- name: Copy liquidpromptrc
  copy:
    src: liquidpromptrc
    dest: ~/.config/liquidpromptrc
    mode: 0640

- name: Find acceptable shells
  command: cat /etc/shells
  register: shells

- name: Add shell to acceptable shells
  shell: echo "{{ shell }}" >> /etc/shells
  become: yes
  when: "{{ shell }}" not in shells

- name: Check current shell
  shell: test $SHELL -ef {{ shell }} && test -e {{ shell }}
  register: current_shell
  ignore_errors: True

- name: Set shell
  command: chsh -s {{ shell }}
  when: current_shell.rc == 1
